# Generated by Django 3.1 on 2021-11-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_age',
            field=models.IntegerField(default='0', verbose_name='Dog Age'),
        ),
        migrations.DeleteModel(
            name='DogReview',
        ),
    ]
