# Generated by Django 3.1 on 2021-11-23 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_area_dog_myuserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myuserinfo',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dog',
            name='dog_gender',
            field=models.CharField(choices=[('수컷', '수컷'), ('암컷', '암컷'), ('중성화', '중성화')], max_length=18, verbose_name='Dog Gender'),
        ),
        migrations.AlterField(
            model_name='myuserinfo',
            name='gender',
            field=models.CharField(choices=[('남자', '남자'), ('여자', '여자'), ('기타', '기타')], max_length=18, verbose_name='Gender'),
        ),
    ]
