# Generated by Django 3.1 on 2021-11-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211128_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='username',
            new_name='owner',
        ),
    ]
